resources:
- repo: self
phases:
- phase: Publish
  pool: 'default'
 
  steps:
  - script: |  
     cd $(Build.ArtifactStagingDirectory)
     echo "hello world" > hi.txt
     echo "bye" > bye.txt
    displayName: Create two text files
    
  - task: PublishBuildArtifacts@1
    displayName: Publish Artifact: drop
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: drop
      publishLocation: Container

- phase: Download
  pool: 'default'
  
  steps:
  - task: DownloadBuildArtifacts@0
    displayName: Download Build Artifacts
    inputs:
      artifactName: drop
