trigger:
- master
jobs:
- job: publishhh
  pool: 'mac'
  steps:
  - bash: |  
     cd $(Build.ArtifactStagingDirectory)
     echo "hello world" > hi.txt
     echo "bye" > bye.txt
     mkdir fortyNineCharactersFollowedByASlashMakesFiftyChar
     cd fortyNineCharactersFollowedByASlashMakesFiftyChar
     echo "GotHere" > 56.txt
     mkdir fortyNineCharactersFollowedByASlashMakesFiftyChar
     cd fortyNineCharactersFollowedByASlashMakesFiftyChar
     echo "GotHere" > 107.txt
     mkdir fortyNineCharactersFollowedByASlashMakesFiftyChar
     cd fortyNineCharactersFollowedByASlashMakesFiftyChar
     echo "GotHere" > 157.txt
     mkdir fortyNineCharactersFollowedByASlashMakesFiftyChar
     cd fortyNineCharactersFollowedByASlashMakesFiftyChar
     echo "GotHere" > 207.txt
     #mkdir fortyNineCharactersFollowedByASlashMakesFiftyChar
     #cd fortyNineCharactersFollowedByASlashMakesFiftyChar
     #echo "GotHere" > 257.txt
     #mkdir fortyNineCharactersFollowedByASlashMakesFiftyChar
     #cd fortyNineCharactersFollowedByASlashMakesFiftyChar
     #echo "GotHere" > 307.txt
     #mkdir fortyNineCharactersFollowedByASlashMakesFiftyChar
     #cd fortyNineCharactersFollowedByASlashMakesFiftyChar
     #echo "GotHere" > 357.txt
    displayName: Create some text files
  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact: drop"
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: drop
      publishLocation: Container
- job: downloaddd
  dependsOn: publishhh
  condition: succeeded()
  pool: 'mac'
  steps:
  - task: DownloadBuildArtifacts@0
    displayName: "Download Build Artifacts"
    inputs:
      artifactName: drop
